trees
badgers-of-kotlin-forest/kotlin-forest pull request #13
Opened 2019-03-14 11:10 UTC by zinoviy23

Генерация деревьев

2019-03-14 11:53 UTC, SerVB requested changes

2019-03-14 11:53 UTC, SerVB commented on back/src/main/kotlin/io/github/badgersOfKotlinForest/kotlinForest/tree/TreeGenerator.kt
> +        val height = Random.nextInt(1, TREE_MAX_HEIGHT)
Судя по <https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.random/-random/next-int.html>, это даст высоту в `1..4`. Можно заюзать аналогичный, но более очевидный метод <https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.random/next-int.html>.

2019-03-14 11:53 UTC, SerVB commented on back/src/main/kotlin/io/github/badgersOfKotlinForest/kotlinForest/tree/TreeGenerator.kt
> +    private fun genTreeElement(elementNumber: Int, treeHeight: Int, prevElement: TreeElement?): TreeElement =
`elementNumber` -> `elementId` более понятно. Сейчас можно спутать с общим количеством элементов.

2019-03-14 11:53 UTC, SerVB commented on back/src/main/kotlin/io/github/badgersOfKotlinForest/kotlinForest/tree/TreeGenerator.kt
> +                        TreeElementType.values().size - 1
Тут не очевидно. Предлагаю делать с помощью .. или until. if можно вынести в extension.

Либо вообще избавиться от завязки на порядок элементов в enum и сделать функцию `randomTypeByPreviousType`. Там уже можно делать `setOf(...).random()`.

2019-03-14 11:53 UTC, SerVB commented on back/src/main/kotlin/io/github/badgersOfKotlinForest/kotlinForest/tree/TreeGenerator.kt
> +    private class AbstractDwelling(override val type: TreeElementType) : Dwelling {
А почему Abstract? Если у нас одна реализация Dwelling планируется, то может вообще интерфейс не вводить?

2019-03-14 11:53 UTC, SerVB commented on back/src/main/kotlin/io/github/badgersOfKotlinForest/kotlinForest/tree/TreeGenerator.kt
> +        return if (Random.nextInt(2) != 0) object : TreeElement {
Для `Random.nextInt(2) != 0` стоит заитродюсить локальную переменную типа `returnDwelling` для понятности.

2019-03-14 11:53 UTC, SerVB commented on back/src/test/kotlin/io/github/badgersOfKotlinForest/kotlinForest/tree/TreeGeneratorTest.kt
> +            assert(prev.type.ordinal <= current.type.ordinal)
Вот тут если будем избавляться от .ordinal, можно сделать мапу `idOfFirstOccurence<TreeElement, Int>`, и потом вручную прописать пару неравенств.

2019-03-14 12:00 UTC, zinoviy23 commented on back/src/main/kotlin/io/github/badgersOfKotlinForest/kotlinForest/tree/TreeGenerator.kt
> +    private class AbstractDwelling(override val type: TreeElementType) : Dwelling {
Я не знаю сколько реализаций будет, сейчас пока одна. Но интерфейс в данном случае точно лишним не будет.

2019-03-14 12:02 UTC, SerVB commented on back/src/main/kotlin/io/github/badgersOfKotlinForest/kotlinForest/tree/TreeGenerator.kt
> +    private class AbstractDwelling(override val type: TreeElementType) : Dwelling {
Слово Abstract тут точно не к месту в любом случае.

2019-03-14 12:07 UTC, Xetd71 commented
Будем считать что с реализацией деревьев в пуле я согласен, вроде добавлений никаких нет к тому, что сказал @SerVB

2019-03-14 12:29 UTC, SerVB commented on back/src/main/kotlin/io/github/badgersOfKotlinForest/kotlinForest/tree/TreeGenerator.kt
> +        return if (isDwelling) object : TreeElement {
Соответственно по смыслу еще нужно поменять местами ветки...

2019-03-15 07:39 UTC, SerVB reviewed
Ты никак не отреагировал на AstractDwelling и на ordinal...

Если мы завязываемся на порядок ordinal, то это нужно прописать рядом с enum, чтобы порядок никто не менял. Но лучше так вообще не делать, опасно. Стоит добавить специальное поле внутрь enum (которое по сути будет делать то же самое, но явно) или поработать с множествами.

Проблема еще в том, что тесты проходят, если поменять порядок элементов в enum, но это очевидно неправильное поведение. В тестах наверно в идеале использовать алгоритм, не совпадающий с кодом.

Например, для такого **неверного** порядка тест **не** падает:
```
    TRUNK,
    ROOT,
    CROWN;
```

Для такого **неверного** падает:
```
    ROOT,
    CROWN,
    TRUNK;
```

Т. е. что-то не так с тестами.

Мне еще кажется, что стоит использовать assert с message, чтобы понимать в логе сразу, что конкретно упало, ну и чтобы понимать, что тестирует тест.

2019-03-15 11:22 UTC, zinoviy23 commented
Последнее это бред. Потому что, чтобы было понятно, тесты как-то именуют. Про интерфейсы тоже
1) Это моё дело, так как он приватный
2) В JVM мире очень часто делают интерфейс и приватный класс имплементацию, чтобы я в будущем мог вместо него что-то вообще другое давать пользователю-программисту. Например много таких пар ```interface A```, ```class AImpl```(В рамках джавы он как бы ```internal```). 

Про зависимость от ordinal: ordinal официально зависит от порядка определения элементов enum(не как поля, которые в JVM могут быть в любом порядке), поэтому я имею право этим пользоваться. 

Про то, что тест может не падать спорно, но я в большей степени согласен. Хотя так много что можно описать, если сломать, то оно сломается, вот блин.

2019-03-15 13:16 UTC, Xetd71 approved these changes

2019-03-15 13:32 UTC, SerVB commented
> чтобы было понятно, тесты как-то именуют.

Но у тебя в одном тесте тестируется куча всего. Тут либо сообщения к ассертам добавить, либо на функции разделить. Общего названия не хватает.

> так как он приватный

Его имя все-равно будет видно при дебаге например.

> interface A, class AImpl

Согласен, что так часто делают (но сам я не считаю, что к каждому классу создавать интерфейс – это лучшая практика). В любом случае, давай хотя бы сделаем так – DwellingImpl.

> поэтому я имею право этим пользоваться

Я за понятность. Тут при объявлении enum не видно, что на ordinal будет такая большая ответственность. Поэтому я предлагаю не использовать низкоуровневневые фичи языка, и реализовать логику более высокоуровнево (выше предлагал несколько решений).

Возможно, ты хочешь оптимизировать. Но это получается получается в данном случае жертвование понятностью. Как и писал Кнут, преждевременная оптимизация — корень всех зол. Так что предлагаю оптимизировать потом, когда у нас будет хоть как-то работаюшее приложение и данные профайлера.

> Хотя так много что можно описать, если сломать, то оно сломается, вот блин.

Недостаток методологии юнит тестирования :) В данном случае стоит добавить еще проверку кейса, который я нашел, который проходит текущие тесты.

2022-02-15 16:38 UTC, SerVB commented
Ох, как давно это было :)

Я сейчас хожу по PRs и закрываю их.

Let me close it because no more work is planned here in the near future, but the PR is shown as pending in my UI

2022-02-15 16:38 UTC, closed without merging